/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as FillFormIdRouteImport } from './routes/fill.$formId'
import { Route as HealthLiveRouteImport } from './routes/health.live'
import { Route as HealthReadyRouteImport } from './routes/health.ready'
import { Route as StudioFormIdRouteImport } from './routes/studio.$formId'
import { Route as ApiHooksDeliverRouteImport } from './routes/api/hooks/deliver'
import { Route as ApiStoragePutRouteImport } from './routes/api/storage/put'
import { Route as ApiStorageTestRouteImport } from './routes/api/storage/test'
import { Route as ApiAgentV1SplatRouteImport } from './routes/api/agent/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const FillFormIdRoute = FillFormIdRouteImport.update({
  id: '/fill/$formId',
  path: '/fill/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioFormIdRoute = StudioFormIdRouteImport.update({
  id: '/studio/$formId',
  path: '/studio/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksDeliverRoute = ApiHooksDeliverRouteImport.update({
  id: '/api/hooks/deliver',
  path: '/api/hooks/deliver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoragePutRoute = ApiStoragePutRouteImport.update({
  id: '/api/storage/put',
  path: '/api/storage/put',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageTestRoute = ApiStorageTestRouteImport.update({
  id: '/api/storage/test',
  path: '/api/storage/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentV1SplatRoute = ApiAgentV1SplatRouteImport.update({
  id: '/api/agent/v1/$',
  path: '/api/agent/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/developer': typeof DeveloperRoute
  '/inbox': typeof InboxRoute
  '/reference': typeof ReferenceRoute
  '/fill/$formId': typeof FillFormIdRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/studio/$formId': typeof StudioFormIdRoute
  '/api/hooks/deliver': typeof ApiHooksDeliverRoute
  '/api/storage/put': typeof ApiStoragePutRoute
  '/api/storage/test': typeof ApiStorageTestRoute
  '/api/agent/v1/$': typeof ApiAgentV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/developer': typeof DeveloperRoute
  '/inbox': typeof InboxRoute
  '/reference': typeof ReferenceRoute
  '/fill/$formId': typeof FillFormIdRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/studio/$formId': typeof StudioFormIdRoute
  '/api/hooks/deliver': typeof ApiHooksDeliverRoute
  '/api/storage/put': typeof ApiStoragePutRoute
  '/api/storage/test': typeof ApiStorageTestRoute
  '/api/agent/v1/$': typeof ApiAgentV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/developer': typeof DeveloperRoute
  '/inbox': typeof InboxRoute
  '/reference': typeof ReferenceRoute
  '/fill/$formId': typeof FillFormIdRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/studio/$formId': typeof StudioFormIdRoute
  '/api/hooks/deliver': typeof ApiHooksDeliverRoute
  '/api/storage/put': typeof ApiStoragePutRoute
  '/api/storage/test': typeof ApiStorageTestRoute
  '/api/agent/v1/$': typeof ApiAgentV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/developer'
    | '/inbox'
    | '/reference'
    | '/fill/$formId'
    | '/health/live'
    | '/health/ready'
    | '/studio/$formId'
    | '/api/hooks/deliver'
    | '/api/storage/put'
    | '/api/storage/test'
    | '/api/agent/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/developer'
    | '/inbox'
    | '/reference'
    | '/fill/$formId'
    | '/health/live'
    | '/health/ready'
    | '/studio/$formId'
    | '/api/hooks/deliver'
    | '/api/storage/put'
    | '/api/storage/test'
    | '/api/agent/v1/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/developer'
    | '/inbox'
    | '/reference'
    | '/fill/$formId'
    | '/health/live'
    | '/health/ready'
    | '/studio/$formId'
    | '/api/hooks/deliver'
    | '/api/storage/put'
    | '/api/storage/test'
    | '/api/agent/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  DeveloperRoute: typeof DeveloperRoute
  InboxRoute: typeof InboxRoute
  ReferenceRoute: typeof ReferenceRoute
  FillFormIdRoute: typeof FillFormIdRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  StudioFormIdRoute: typeof StudioFormIdRoute
  ApiHooksDeliverRoute: typeof ApiHooksDeliverRoute
  ApiStoragePutRoute: typeof ApiStoragePutRoute
  ApiStorageTestRoute: typeof ApiStorageTestRoute
  ApiAgentV1SplatRoute: typeof ApiAgentV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill/$formId': {
      id: '/fill/$formId'
      path: '/fill/$formId'
      fullPath: '/fill/$formId'
      preLoaderRoute: typeof FillFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$formId': {
      id: '/studio/$formId'
      path: '/studio/$formId'
      fullPath: '/studio/$formId'
      preLoaderRoute: typeof StudioFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/deliver': {
      id: '/api/hooks/deliver'
      path: '/api/hooks/deliver'
      fullPath: '/api/hooks/deliver'
      preLoaderRoute: typeof ApiHooksDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/put': {
      id: '/api/storage/put'
      path: '/api/storage/put'
      fullPath: '/api/storage/put'
      preLoaderRoute: typeof ApiStoragePutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/test': {
      id: '/api/storage/test'
      path: '/api/storage/test'
      fullPath: '/api/storage/test'
      preLoaderRoute: typeof ApiStorageTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/v1/$': {
      id: '/api/agent/v1/$'
      path: '/api/agent/v1/$'
      fullPath: '/api/agent/v1/$'
      preLoaderRoute: typeof ApiAgentV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  DeveloperRoute: DeveloperRoute,
  InboxRoute: InboxRoute,
  ReferenceRoute: ReferenceRoute,
  FillFormIdRoute: FillFormIdRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  StudioFormIdRoute: StudioFormIdRoute,
  ApiHooksDeliverRoute: ApiHooksDeliverRoute,
  ApiStoragePutRoute: ApiStoragePutRoute,
  ApiStorageTestRoute: ApiStorageTestRoute,
  ApiAgentV1SplatRoute: ApiAgentV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
