import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { formatValue } from "./pdf.ts";
import { flattenInputs } from "./tree.ts";
import type { FormComponent, PdfAlign, PdfPlacement, PdfTheme } from "./types.ts";

export const PDF_PAGE = { width: 612, height: 792 };

export const DEFAULT_PDF_THEME: PdfTheme = {
  accent: "#1c3d36",
  border: "box",
  zebra: true,
  pageNumbers: true,
  header: true,
  footer: "Generated by Meridian",
  columns: 1,
};

export function parseHex(input: string): { r: number; g: number; b: number } {
  const hex = input.trim().replace("#", "");
  if (!/^[0-9a-fA-F]{6}$/.test(hex)) return { r: 0.11, g: 0.24, b: 0.21 };
  return {
    r: Number.parseInt(hex.slice(0, 2), 16) / 255,
    g: Number.parseInt(hex.slice(2, 4), 16) / 255,
    b: Number.parseInt(hex.slice(4, 6), 16) / 255,
  };
}

export function clampPercent(value: number, min = 2, max = 96): number {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, value));
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

/** Form.io overlay units are CSS pixels on a letter page. Percents are 0–100. */
export function parseOverlayLength(value: unknown, span: number): number | null {
  if (typeof value === "number" && Number.isFinite(value)) {
    if (value >= 0 && value <= 100) return value;
    return (value / span) * 100;
  }
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  if (trimmed.endsWith("%")) {
    const n = Number(trimmed.slice(0, -1));
    return Number.isFinite(n) ? n : null;
  }
  const px = trimmed.endsWith("px") ? Number(trimmed.slice(0, -2)) : Number(trimmed);
  if (!Number.isFinite(px)) return null;
  if (trimmed.endsWith("px") || px > 100) return (px / span) * 100;
  return px;
}

export function overlayToPlacement(overlay: Record<string, unknown>, previous?: PdfPlacement): PdfPlacement | null {
  const page = Number(overlay.page ?? previous?.page ?? 1);
  const x = parseOverlayLength(overlay.left, PDF_PAGE.width);
  const y = parseOverlayLength(overlay.top, PDF_PAGE.height);
  const w = parseOverlayLength(overlay.width, PDF_PAGE.width);
  const h = parseOverlayLength(overlay.height, PDF_PAGE.height);
  if (![page, x, y, w, h].every((item) => item != null && Number.isFinite(item))) return null;
  return {
    ...previous,
    page: Math.max(1, Math.floor(page)),
    x: x as number,
    y: y as number,
    w: w as number,
    h: h as number,
  };
}

export function placementToOverlay(pdf: PdfPlacement): { page: number; left: string; top: string; width: string; height: string } {
  return {
    page: pdf.page,
    left: `${round((pdf.x / 100) * PDF_PAGE.width)}px`,
    top: `${round((pdf.y / 100) * PDF_PAGE.height)}px`,
    width: `${round((pdf.w / 100) * PDF_PAGE.width)}px`,
    height: `${round((pdf.h / 100) * PDF_PAGE.height)}px`,
  };
}

export function withPdfPlacement(component: FormComponent, pdf: PdfPlacement | undefined): Pick<FormComponent, "pdf" | "formio"> {
  const formio = { ...(component.formio ?? {}) };
  if (!pdf) {
    delete formio.overlay;
    return { pdf: undefined, formio };
  }
  formio.overlay = placementToOverlay(pdf);
  return { pdf, formio };
}

export function defaultPlacement(index: number, page = 1): PdfPlacement {
  const row = index % 10;
  const column = Math.floor(index / 10) % 2;
  return {
    page,
    x: 8 + column * 46,
    y: 8 + row * 8,
    w: 40,
    h: 5.5,
    fontSize: 11,
    align: "left",
    font: "Helvetica",
    showLabel: true,
  };
}

export function sampleSubmission(components: FormComponent[]): Record<string, unknown> {
  const data: Record<string, unknown> = {};
  for (const component of flattenInputs(components)) {
    if (component.defaultValue !== undefined && component.defaultValue !== null && component.defaultValue !== "") {
      data[component.key] = component.defaultValue;
      continue;
    }
    switch (component.type) {
      case "checkbox":
      case "toggle":
        data[component.key] = true;
        break;
      case "select":
      case "radio":
        data[component.key] = component.values?.[0]?.value ?? "a";
        break;
      case "selectboxes":
        data[component.key] = (component.values ?? []).slice(0, 2).map((item) => item.value);
        break;
      case "number":
      case "currency":
      case "slider":
      case "rating":
        data[component.key] = component.defaultValue ?? component.min ?? 1;
        break;
      case "date":
        data[component.key] = "2026-09-28";
        break;
      case "datetime":
        data[component.key] = "2026-09-28T15:00";
        break;
      case "time":
        data[component.key] = "15:04";
        break;
      case "email":
        data[component.key] = "ada@example.com";
        break;
      case "phone":
        data[component.key] = "+1 202 555 0147";
        break;
      case "url":
        data[component.key] = "https://example.com";
        break;
      case "address":
        data[component.key] = { line1: "1 Market Street", city: "San Francisco", region: "CA", postalCode: "94105", country: "US" };
        break;
      case "file":
        data[component.key] = { name: "attachment.pdf", size: 1200, type: "application/pdf", sha256: "abc123" };
        break;
      case "signature":
        data[component.key] = "Ada Lovelace";
        break;
      case "captcha":
        data[component.key] = { passed: true };
        break;
      default:
        data[component.key] = component.placeholder || component.label || component.key;
    }
  }
  return data;
}

function optionLabel(component: FormComponent, value: string): string {
  return component.values?.find((item) => item.value === value)?.label ?? value;
}

export function formatPdfValue(component: FormComponent, value: unknown): string {
  if (value == null || value === "") return "";
  if (component.type === "captcha") return "Verified";
  if (component.type === "checkbox" || component.type === "toggle") return value === true ? "Yes" : "No";
  if (component.type === "select" || component.type === "radio") return optionLabel(component, String(value));
  if (component.type === "selectboxes" && Array.isArray(value)) return value.map((item) => optionLabel(component, String(item))).join(", ");
  const format = component.pdf?.format ?? "";
  if ((component.type === "currency" || format === "currency") && (typeof value === "number" || typeof value === "string")) {
    const amount = Number(value);
    if (Number.isFinite(amount)) {
      return new Intl.NumberFormat("en-US", { style: "currency", currency: component.currency || "USD" }).format(amount);
    }
  }
  if ((component.type === "date" || component.type === "datetime") && format.includes("YYYY")) {
    const iso = String(value).slice(0, 10);
    const [year, month, day] = iso.split("-");
    if (year && month && day) return format.replace("YYYY", year).replace("MM", month).replace("DD", day);
  }
  const text = formatValue(value);
  if (format === "upper") return text.toUpperCase();
  if (format === "lower") return text.toLowerCase();
  return text;
}

export function safePdfText(input: string): string {
  let out = "";
  for (const ch of input) {
    const code = ch.codePointAt(0) ?? 63;
    if (code === 10 || code === 13 || code === 9) {
      out += " ";
      continue;
    }
    out += (code >= 32 && code <= 126) || (code >= 160 && code <= 255) ? ch : "?";
  }
  return out;
}

function boxOf(pdf: PdfPlacement, pageWidth: number, pageHeight: number) {
  const width = (pdf.w / 100) * pageWidth;
  const height = (pdf.h / 100) * pageHeight;
  const x = (pdf.x / 100) * pageWidth;
  const y = pageHeight - ((pdf.y / 100) * pageHeight + height);
  return { x, y, width: Math.max(8, width), height: Math.max(8, height) };
}

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = safePdfText(text).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (line && font.widthOfTextAtSize(next, size) > maxWidth) {
      lines.push(line);
      line = word;
    } else line = next;
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

function drawAligned(page: PDFPage, text: string, font: PDFFont, size: number, box: { x: number; y: number; width: number; height: number }, align: PdfAlign, y: number) {
  const safe = safePdfText(text);
  const width = font.widthOfTextAtSize(safe, size);
  let x = box.x + 3;
  if (align === "center") x = box.x + Math.max(2, (box.width - width) / 2);
  if (align === "right") x = box.x + Math.max(2, box.width - width - 3);
  page.drawText(safe, { x, y, size, font, color: rgb(0.08, 0.09, 0.12) });
}

function drawField(
  page: PDFPage,
  component: FormComponent,
  font: PDFFont,
  bold: PDFFont,
  oblique: PDFFont,
  courier: PDFFont,
  value: string,
  mode: "blank" | "filled",
  theme: PdfTheme,
  onBackground: boolean,
) {
  const placement = component.pdf;
  if (!placement) return;
  const size = page.getSize();
  const box = boxOf(placement, size.width, size.height);
  const accent = parseHex(theme.accent);
  const ink = rgb(accent.r, accent.g, accent.b);
  const chosen = placement.font === "Helvetica-Bold" ? bold : placement.font === "Courier" ? courier : placement.font === "Helvetica-Oblique" || component.type === "signature" ? oblique : font;
  const align = placement.align ?? "left";
  const fontSize = Math.max(8, Math.min(placement.fontSize ?? 11, box.height - 4));
  if (component.type === "checkbox" || component.type === "toggle") {
    const side = Math.min(12, box.height - 2);
    const cx = box.x + 2;
    const cy = box.y + (box.height - side) / 2;
    page.drawRectangle({ x: cx, y: cy, width: side, height: side, borderWidth: 1, borderColor: ink });
    if (mode === "filled" && value === "Yes") {
      page.drawLine({ start: { x: cx + 2, y: cy + side * 0.45 }, end: { x: cx + side * 0.4, y: cy + 2 }, thickness: 1.3, color: ink });
      page.drawLine({ start: { x: cx + side * 0.4, y: cy + 2 }, end: { x: cx + side - 2, y: cy + side - 2 }, thickness: 1.3, color: ink });
    }
    const caption = mode === "blank" || placement.showLabel !== false ? component.label : "";
    if (caption) drawAligned(page, caption, font, Math.min(fontSize, 10), { ...box, x: box.x + side + 4, width: box.width - side - 6 }, align, cy + 2);
    return;
  }
  if (theme.border === "box" && !onBackground) {
    page.drawRectangle({ x: box.x, y: box.y, width: box.width, height: box.height, color: rgb(0.97, 0.98, 0.96), borderColor: ink, borderWidth: 0.8 });
  } else if (theme.border !== "none") {
    const y = theme.border === "underline" ? box.y + 1 : box.y;
    page.drawLine({ start: { x: box.x, y }, end: { x: box.x + box.width, y: theme.border === "box" ? box.y : y }, thickness: theme.border === "box" ? 0.8 : 0.7, color: ink });
    if (theme.border === "box") {
      page.drawRectangle({ x: box.x, y: box.y, width: box.width, height: box.height, borderColor: ink, borderWidth: 0.7 });
    }
  }
  const showLabel = placement.showLabel !== false;
  const label = showLabel ? component.label : "";
  const body = mode === "blank" ? label : value;
  if (showLabel && mode === "filled" && label && box.height > 16) {
    page.drawText(safePdfText(label).slice(0, 80), { x: box.x + 3, y: box.y + box.height - 9, size: 7, font, color: rgb(0.35, 0.4, 0.38) });
  }
  const text = mode === "filled" ? body || "" : label;
  const lines = wrapText(text || " ", chosen, fontSize, Math.max(8, box.width - 6));
  let cursor = box.y + box.height - (showLabel && mode === "filled" && box.height > 16 ? fontSize + 10 : fontSize + 2);
  for (const line of lines) {
    if (cursor < box.y + 1) break;
    drawAligned(page, line, chosen, fontSize, box, align, cursor);
    cursor -= fontSize + 1.5;
  }
  if (component.type === "signature" && mode === "filled" && value) {
    page.drawLine({ start: { x: box.x + 2, y: box.y + 3 }, end: { x: box.x + box.width - 2, y: box.y + 3 }, thickness: 0.5, color: ink });
  }
}

function stampFooter(page: PDFPage, font: PDFFont, theme: PdfTheme, label: string) {
  if (!theme.pageNumbers && !theme.footer) return;
  const { width } = page.getSize();
  page.drawLine({ start: { x: 40, y: 32 }, end: { x: width - 40, y: 32 }, thickness: 0.4, color: rgb(0.75, 0.78, 0.76) });
  if (theme.footer) page.drawText(safePdfText(theme.footer).slice(0, 80), { x: 40, y: 18, size: 8, font, color: rgb(0.4, 0.44, 0.42) });
  if (theme.pageNumbers) page.drawText(label, { x: width - 70, y: 18, size: 8, font, color: rgb(0.4, 0.44, 0.42) });
}

function drawRecord(page: PDFPage, font: PDFFont, bold: PDFFont, title: string, rows: { label: string; value: string }[], startAt: number, theme: PdfTheme, pageLabel: string): number {
  const { width, height } = page.getSize();
  const accent = parseHex(theme.accent);
  const ink = rgb(accent.r, accent.g, accent.b);
  let y = height - 48;
  if (theme.header) {
    page.drawRectangle({ x: 0, y: height - 72, width, height: 72, color: ink });
    page.drawText(safePdfText(title).slice(0, 70), { x: 40, y: height - 38, size: 16, font: bold, color: rgb(1, 1, 1) });
    page.drawText(safePdfText(theme.footer || "Submission record"), { x: 40, y: height - 56, size: 9, font, color: rgb(0.9, 0.94, 0.92) });
    y = height - 96;
  }
  const gap = 36;
  const columns = theme.columns === 2 ? 2 : 1;
  const colWidth = (width - 80 - (columns === 2 ? 16 : 0)) / columns;
  let index = startAt;
  while (index < rows.length) {
    if (y < 64) break;
    for (let column = 0; column < columns && index < rows.length; column += 1) {
      const row = rows[index]!;
      const x = 40 + column * (colWidth + 16);
      if (theme.zebra && Math.floor((index - startAt) / columns) % 2 === 0) {
        page.drawRectangle({ x, y: y - 8, width: colWidth, height: 30, color: rgb(0.95, 0.97, 0.95) });
      }
      page.drawRectangle({ x, y: y - 8, width: 3, height: 30, color: ink });
      page.drawText(safePdfText(row.label).slice(0, 42), { x: x + 8, y: y + 10, size: 7, font, color: rgb(0.32, 0.38, 0.36) });
      const line = wrapText(row.value || "—", bold, 10, colWidth - 16)[0] ?? "—";
      page.drawText(safePdfText(line), { x: x + 8, y: y - 4, size: 10, font: bold, color: rgb(0.08, 0.1, 0.1) });
      index += 1;
    }
    y -= gap;
  }
  if (theme.pageNumbers || theme.footer) {
    page.drawLine({ start: { x: 40, y: 32 }, end: { x: width - 40, y: 32 }, thickness: 0.4, color: rgb(0.75, 0.78, 0.76) });
    page.drawText(safePdfText(theme.footer), { x: 40, y: 18, size: 8, font, color: rgb(0.4, 0.44, 0.42) });
    page.drawText(pageLabel, { x: width - 80, y: 18, size: 8, font, color: rgb(0.4, 0.44, 0.42) });
  }
  return index;
}

export async function renderFormPdf(input: {
  title: string;
  pageCount: number;
  components: FormComponent[];
  data: Record<string, unknown>;
  background?: Uint8Array | null;
  mode: "blank" | "filled";
  appendRecord?: boolean;
  theme?: Partial<PdfTheme>;
}): Promise<Uint8Array> {
  const theme = { ...DEFAULT_PDF_THEME, ...input.theme };
  const wanted = Math.max(1, input.pageCount);
  const onBackground = !!input.background?.byteLength;
  const doc = onBackground
    ? await PDFDocument.load(input.background!, { ignoreEncryption: true })
    : await PDFDocument.create();
  while (doc.getPageCount() < wanted) doc.addPage([PDF_PAGE.width, PDF_PAGE.height]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const oblique = await doc.embedFont(StandardFonts.HelveticaOblique);
  const courier = await doc.embedFont(StandardFonts.Courier);
  const fields = flattenInputs(input.components).filter((component) => component.pdf && component.type !== "content" && component.type !== "button" && component.type !== "review");
  for (const component of fields) {
    const page = doc.getPage((component.pdf?.page ?? 1) - 1);
    if (!page) continue;
    const value = input.mode === "filled" ? formatPdfValue(component, input.data[component.key]) : "";
    drawField(page, component, font, bold, oblique, courier, value, input.mode, theme, onBackground);
  }
  if (!onBackground && theme.pageNumbers) {
    doc.getPages().slice(0, wanted).forEach((page, index) => stampFooter(page, font, theme, `Page ${index + 1}`));
  }
  if (fields.length === 0 && !onBackground) {
    const page = doc.getPage(0);
    const accent = parseHex(theme.accent);
    if (theme.header) page.drawRectangle({ x: 0, y: page.getSize().height - 72, width: page.getSize().width, height: 72, color: rgb(accent.r, accent.g, accent.b) });
    page.drawText(safePdfText(input.title || "Form"), { x: 40, y: page.getSize().height - (theme.header ? 40 : 64), size: 18, font: bold, color: theme.header ? rgb(1, 1, 1) : rgb(0.08, 0.09, 0.12) });
    page.drawText("No fields are placed on the page yet.", { x: 40, y: page.getSize().height - (theme.header ? 96 : 88), size: 11, font, color: theme.header ? rgb(0.2, 0.24, 0.22) : rgb(0.25, 0.28, 0.33) });
  }
  if (input.mode === "filled" && input.appendRecord !== false) {
    const rows = flattenInputs(input.components)
      .filter((component) => component.type !== "content" && component.type !== "button" && component.type !== "review" && component.type !== "captcha")
      .map((component) => ({ label: component.label || component.key, value: formatPdfValue(component, input.data[component.key]) || "—" }));
    let cursor = 0;
    let guard = 0;
    while (cursor < rows.length && guard < 12) {
      const page = doc.addPage([PDF_PAGE.width, PDF_PAGE.height]);
      const before = cursor;
      cursor = drawRecord(page, font, bold, cursor === 0 ? input.title : `${input.title} (continued)`, rows, cursor, theme, `Record ${guard + 1}`);
      if (cursor === before) break;
      guard += 1;
    }
  }
  return doc.save();
}

export function exportOverlays(components: FormComponent[]): { key: string; label: string; overlay: ReturnType<typeof placementToOverlay> }[] {
  return flattenInputs(components)
    .filter((component) => component.pdf)
    .map((component) => ({ key: component.key, label: component.label, overlay: placementToOverlay(component.pdf!) }));
}

export function importOverlayList(raw: unknown): { key: string; pdf: PdfPlacement }[] {
  const list = Array.isArray(raw) ? raw : raw && typeof raw === "object" && Array.isArray((raw as { components?: unknown }).components) ? (raw as { components: unknown[] }).components : [];
  const placed: { key: string; pdf: PdfPlacement }[] = [];
  for (const item of list) {
    if (!item || typeof item !== "object") continue;
    const record = item as { key?: unknown; overlay?: unknown };
    const key = typeof record.key === "string" ? record.key : "";
    if (!key || !record.overlay || typeof record.overlay !== "object") continue;
    const pdf = overlayToPlacement(record.overlay as Record<string, unknown>);
    if (pdf) placed.push({ key, pdf });
  }
  return placed;
}
